#!/bin/bash
# Quick Setup Script for Supabase Integration

echo "========================================"
echo "  LogiEdge Supabase Setup"
echo "========================================"
echo ""
echo "1️⃣  Get Supabase Credentials:"
echo "   - Go to: supabase.com"
echo "   - Open your project"
echo "   - Click Settings → API"
echo "   - Copy Project URL and Anon Key"
echo ""
echo "2️⃣  Update backend/.env:"
echo ""
echo "   SUPABASE_URL=https://your-project.supabase.co"
echo "   SUPABASE_ANON_KEY=your-anon-key-here"
echo ""
echo "3️⃣  Update frontend/frontend/.env.local:"
echo ""
echo "   VITE_SUPABASE_URL=https://your-project.supabase.co"
echo "   VITE_SUPABASE_ANON_KEY=your-anon-key-here"
echo "   VITE_API_URL=http://localhost:5000"
echo ""
echo "4️⃣  Create Supabase Storage Buckets:"
echo "   - Go to Storage in Supabase dashboard"
echo "   - Create: invoices (public)"
echo "   - Create: customer-docs (public)"
echo "   - Create: attachments (public)"
echo ""
echo "5️⃣  Restart Servers:"
echo ""
echo "   # Terminal 1 - Backend"
echo "   cd backend"
echo "   npm start"
echo ""
echo "   # Terminal 2 - Frontend"
echo "   cd frontend/frontend"
echo "   npm run dev"
echo ""
echo "✅ Done! Your app is ready with Supabase Storage"
echo ""
